"""Test selector — the workflow's "central de testes".

Maps a working-tree diff to the *relevant* subset of the pytest suite so a phase
can iterate fast without running all ~1400 tests, while a conservative gate
still catches contract regressions.

Two-layer catalog (see `.ai/tests/README.md`):

* ``catalog.generated.yaml`` — AUTO-GENERATED by ``--sync``. Group membership is
  derived from the ``test_<area>_*.py`` filename convention; ``covers`` (the
  source files each group is coupled to) is derived by a *static scan* of the
  test source for repo-relative path literals (both ``"a/b.js"`` single strings
  and segmented ``"a" / "b" / "c.js"`` joins), validated by file existence.
* ``catalog.overlay.yaml`` — the small CURATED layer: ``aliases`` (fold area
  tokens into canonical groups, e.g. ``pty -> terminals``), ``always`` (groups
  that always run at the gate because they guard scaffold-wide invariants), and
  ``extra_covers`` (couplings the scanner can't see).

The scan is intentionally coverage-free: it never runs pytest, so ``--sync`` is
instant and *deterministic* — which is what lets the lockfile meta-test
(`tests/test_catalog.py`) assert the committed file is in sync by re-deriving it
in memory.

CLI::

    python .ai/scripts/select_tests.py --sync            # regenerate the catalog
    python .ai/scripts/select_tests.py --sync --check    # exit 1 if stale (no write)
    python .ai/scripts/select_tests.py --fast            # subset for the touched groups
    python .ai/scripts/select_tests.py --gate            # touched + always (validation gate)
    python .ai/scripts/select_tests.py --list            # human summary of the selection
    python .ai/scripts/select_tests.py --gate --run      # run pytest instead of printing
    python .ai/scripts/select_tests.py --gate --base main # diff against a ref, not HEAD
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

import yaml

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #

REPO_ROOT = Path(__file__).resolve().parents[2]
TESTS_DIR = REPO_ROOT / "tests"
CATALOG_DIR = REPO_ROOT / ".ai" / "tests"
GENERATED_PATH = CATALOG_DIR / "catalog.generated.yaml"
OVERLAY_PATH = CATALOG_DIR / "catalog.overlay.yaml"

GENERATED_HEADER = (
    "# AUTO-GENERATED by .ai/scripts/select_tests.py --sync. DO NOT EDIT BY HAND.\n"
    "# Group membership comes from the test_<area>_*.py filename convention;\n"
    "# `covers` is a static scan of each test's repo-relative path literals.\n"
    "# Curated knobs (aliases / always / extra_covers) live in catalog.overlay.yaml.\n"
)

# A changed file that matches no group AND is not inert forces the gate to fall
# back to the full suite (fail-safe). These prefixes/suffixes are inert: editing
# them cannot change runtime behaviour the suite asserts, so they never trigger
# a fallback on their own.
INERT_PREFIXES = (
    ".ai/local/",
    ".ai/plans/",
    ".ai/specs/",
    ".ai/memory",
    ".ai/decisions.md",
    ".ai/TODO.md",
    ".ai/council/runs/",
    ".ai/eval/results/",
    ".worktrees/",
    "docs/",
    "tmp/",
    ".github/",
)
INERT_SUFFIXES = (".gitkeep", ".log", ".err")

# Extensions whose edits the suite can plausibly assert against. A changed file
# with one of these that maps to no group is "unmapped" → fallback. Other
# extensions (images, lockfiles, …) are treated as inert.
SOURCE_SUFFIXES = (".py", ".js", ".html", ".css", ".md", ".yaml", ".yml", ".json", ".sh")


# --------------------------------------------------------------------------- #
# Membership: filename convention → canonical group id
# --------------------------------------------------------------------------- #

_AREA_RE = re.compile(r"^test_([a-z0-9]+)")


def area_of(stem: str) -> str | None:
    """Leading area token of a ``test_<area>_*`` filename stem, or None."""
    m = _AREA_RE.match(stem)
    return m.group(1) if m else None


def discover_test_files(root: Path = REPO_ROOT) -> list[Path]:
    return sorted((root / "tests").glob("test_*.py"))


# --------------------------------------------------------------------------- #
# Covers: static scan of repo-relative path literals in test source
# --------------------------------------------------------------------------- #

# Form A — a single quoted string that already contains a path separator,
# e.g. _read(".ai/workflow/dispatch.md").
_SINGLE_RE = re.compile(r"""['"]([^'"\n]*?/[^'"\n]*?)['"]""")

# Form B — segments joined by the `/` operator,
# e.g. Path(...) / ".ai" / "dashboard" / "app" / "jobs.js".
# Match runs of >=2 quoted segments separated by `/` and reconstruct the path.
_SEGMENT_RUN_RE = re.compile(
    r"""(['"][^'"\n]+['"]\s*/\s*)+['"][^'"\n]+['"]"""
)
_QUOTED_RE = re.compile(r"""['"]([^'"\n]+)['"]""")


def _normalize(candidate: str) -> str:
    # Strip a leading "./" only — NOT a charset lstrip, which would eat the dot
    # of dotdirs like ".ai" / ".claude" and turn ".ai/x" into "ai/x".
    rel = candidate.replace("\\", "/").strip()
    if rel.startswith("./"):
        rel = rel[2:]
    return rel.strip("/")


def extract_repo_paths(text: str, root: Path = REPO_ROOT) -> set[str]:
    """Repo-relative paths to existing files referenced literally in ``text``.

    Validated by existence so over-capture is harmless: a reconstructed string
    that isn't a real repo file is dropped. Self-references under ``tests/`` are
    excluded — editing a test already triggers its own group via membership.
    """
    found: set[str] = set()

    def _consider(raw: str) -> None:
        rel = _normalize(raw)
        if not rel or rel.startswith("tests/"):
            return
        # Inert paths (runtime-generated ledgers under .ai/local/, gitignored
        # state, non-source suffixes) must never enter `covers`: they may be
        # absent at sync time and created by a later test run, which would make
        # the scan non-deterministic and break the lockfile invariant.
        if _is_inert(rel):
            return
        if (root / rel).is_file():
            found.add(rel)

    # Form A
    for m in _SINGLE_RE.finditer(text):
        _consider(m.group(1))

    # Form B
    for run in _SEGMENT_RUN_RE.finditer(text):
        segments = _QUOTED_RE.findall(run.group(0))
        if len(segments) >= 2:
            _consider("/".join(segments))

    return found


# --------------------------------------------------------------------------- #
# Overlay (curated layer)
# --------------------------------------------------------------------------- #


def load_overlay(root: Path = REPO_ROOT) -> dict:
    path = root / ".ai" / "tests" / "catalog.overlay.yaml"
    if not path.is_file():
        return {"aliases": {}, "always": [], "extra_covers": {}}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    data.setdefault("aliases", {})
    data.setdefault("always", [])
    data.setdefault("extra_covers", {})
    return data


def canonical_group(area: str, aliases: dict[str, str]) -> str:
    return aliases.get(area, area)


# --------------------------------------------------------------------------- #
# Build (sync) — derive the generated catalog
# --------------------------------------------------------------------------- #


def build_catalog(root: Path = REPO_ROOT, overlay: dict | None = None) -> dict:
    """Derive ``{groups: {id: {tests: [...], covers: [...]}}}`` from disk.

    Pure function of (test files, their contents, overlay). No subprocess, no
    coverage, no clock — so the result is deterministic and lockfile-checkable.
    """
    if overlay is None:
        overlay = load_overlay(root)
    aliases = overlay.get("aliases", {})
    extra_covers = overlay.get("extra_covers", {})

    groups: dict[str, dict[str, set[str]]] = {}
    for test_path in discover_test_files(root):
        area = area_of(test_path.stem)
        if area is None:
            continue
        gid = canonical_group(area, aliases)
        bucket = groups.setdefault(gid, {"tests": set(), "covers": set()})
        bucket["tests"].add(f"tests/{test_path.name}")
        bucket["covers"] |= extract_repo_paths(test_path.read_text(encoding="utf-8"), root)

    # Fold curated extra_covers in (escape hatch for couplings the scan misses).
    for gid, paths in extra_covers.items():
        bucket = groups.setdefault(gid, {"tests": set(), "covers": set()})
        for rel in paths:
            if (root / rel).is_file():
                bucket["covers"].add(rel)

    return {
        "groups": {
            gid: {
                "tests": sorted(bucket["tests"]),
                "covers": sorted(bucket["covers"]),
            }
            for gid, bucket in sorted(groups.items())
        }
    }


def dump_catalog(catalog: dict) -> str:
    body = yaml.safe_dump(catalog, sort_keys=True, default_flow_style=False, allow_unicode=True)
    return GENERATED_HEADER + body


def load_generated(root: Path = REPO_ROOT) -> dict:
    path = root / ".ai" / "tests" / "catalog.generated.yaml"
    if not path.is_file():
        raise FileNotFoundError(
            f"{path} missing — run: python .ai/scripts/select_tests.py --sync"
        )
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {"groups": {}}


def is_in_sync(root: Path = REPO_ROOT) -> bool:
    """True iff the committed generated catalog equals a fresh in-memory build."""
    try:
        committed = load_generated(root).get("groups", {})
    except FileNotFoundError:
        return False
    return committed == build_catalog(root).get("groups", {})


# --------------------------------------------------------------------------- #
# Diff → selection
# --------------------------------------------------------------------------- #


def git_changed(root: Path = REPO_ROOT, base: str = "HEAD") -> list[str]:
    """Repo-relative changed paths: diff vs ``base`` plus untracked files."""
    def _git(*args: str) -> list[str]:
        out = subprocess.run(
            ["git", "-C", str(root), *args],
            capture_output=True, text=True, check=False,
        )
        return [ln.strip() for ln in out.stdout.splitlines() if ln.strip()]

    changed = set(_git("diff", "--name-only", base))
    changed |= set(_git("ls-files", "--others", "--exclude-standard"))
    return sorted(changed)


def _is_inert(rel: str) -> bool:
    if rel.startswith(INERT_PREFIXES):
        return True
    if rel.endswith(INERT_SUFFIXES):
        return True
    return not rel.endswith(SOURCE_SUFFIXES)


def select(catalog: dict, overlay: dict, changed: list[str]) -> dict:
    """Resolve changed files to touched/gate group sets and unmapped files."""
    groups = catalog.get("groups", {})
    always = [g for g in overlay.get("always", []) if g in groups]

    # Reverse indexes.
    group_of_test: dict[str, str] = {}
    covers_index: dict[str, list[str]] = {}
    for gid, g in groups.items():
        for t in g.get("tests", []):
            group_of_test[t] = gid
        for c in g.get("covers", []):
            covers_index.setdefault(c, []).append(gid)

    touched: set[str] = set()
    unmapped: list[str] = []
    for rel in changed:
        if rel in group_of_test:           # a test file changed → its own group
            touched.add(group_of_test[rel])
        elif rel in covers_index:          # a covered source file changed
            touched.update(covers_index[rel])
        elif not _is_inert(rel):           # source-like but unmapped → fail-safe
            unmapped.append(rel)

    gate = set(touched) | set(always)
    return {
        "touched": sorted(touched),
        "always": sorted(always),
        "gate": sorted(gate),
        "unmapped": sorted(unmapped),
        "fallback": bool(unmapped),
    }


def _tests_for(catalog: dict, group_ids: list[str]) -> list[str]:
    groups = catalog.get("groups", {})
    files: set[str] = set()
    for gid in group_ids:
        files.update(groups.get(gid, {}).get("tests", []))
    return sorted(files)


def _shquote(token: str) -> str:
    """Quote a token for display so a copy-pasted command survives the shell.
    ``-m "not slow"`` must stay one argument; double quotes work in both bash
    and PowerShell."""
    return f'"{token}"' if (" " in token or not token) else token


def _pytest_cmd(test_files: list[str], *, gate: bool) -> list[str]:
    cmd = ["pytest", *test_files, "-n", "auto"]
    if gate:
        # The gate is the fast loop — exclude slow install/subprocess tests.
        # Medium/large or elevated-risk tasks run the true full suite separately.
        cmd += ["-m", "not slow"]
    return cmd


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def _cmd_sync(args: argparse.Namespace) -> int:
    fresh = build_catalog()
    if args.check:
        if is_in_sync():
            print("catalog in sync")
            return 0
        print(
            "catalog.generated.yaml is STALE — run: "
            "python .ai/scripts/select_tests.py --sync",
            file=sys.stderr,
        )
        return 1
    CATALOG_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_PATH.write_text(dump_catalog(fresh), encoding="utf-8", newline="\n")
    n_groups = len(fresh["groups"])
    n_tests = sum(len(g["tests"]) for g in fresh["groups"].values())
    print(f"wrote {GENERATED_PATH.relative_to(REPO_ROOT)} — {n_groups} groups, {n_tests} test files")
    return 0


def _resolve_selection(args: argparse.Namespace) -> tuple[dict, dict, dict]:
    catalog = load_generated()
    overlay = load_overlay()
    changed = git_changed(base=args.base)
    sel = select(catalog, overlay, changed)
    return catalog, sel, {"changed": changed}


def _emit_command(catalog: dict, sel: dict, *, gate: bool, run: bool) -> int:
    if gate and sel["fallback"]:
        # Fail-safe: an unmapped source file changed — run everything (minus slow).
        cmd = ["pytest", "-m", "not slow", "-n", "auto"]
        print(
            "fallback: unmapped change(s) → full suite: " + ", ".join(sel["unmapped"]),
            file=sys.stderr,
        )
    else:
        group_ids = sel["gate"] if gate else sel["touched"]
        files = _tests_for(catalog, group_ids)
        if not files:
            print("no touched groups — nothing to run", file=sys.stderr)
            return 0
        cmd = _pytest_cmd(files, gate=gate)

    if run:
        return subprocess.run(cmd, cwd=str(REPO_ROOT)).returncode
    print(" ".join(_shquote(c) for c in cmd))
    return 0


def _cmd_list(args: argparse.Namespace) -> int:
    catalog, sel, extra = _resolve_selection(args)
    print(f"changed files : {len(extra['changed'])}")
    print(f"touched groups: {', '.join(sel['touched']) or '(none)'}")
    print(f"always groups : {', '.join(sel['always']) or '(none)'}")
    print(f"gate groups   : {', '.join(sel['gate']) or '(none)'}")
    if sel["unmapped"]:
        print(f"unmapped      : {', '.join(sel['unmapped'])}  -> gate falls back to full suite")
    fast = _tests_for(catalog, sel["touched"])
    gate = _tests_for(catalog, sel["gate"])
    print(f"fast subset   : {len(fast)} test files")
    print(f"gate subset   : {len(gate)} test files" + (" (overridden by fallback)" if sel["fallback"] else ""))
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Map a diff to the relevant pytest subset.")
    p.add_argument("--base", default="HEAD", help="git ref to diff against (default: HEAD)")
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--sync", action="store_true", help="regenerate catalog.generated.yaml")
    mode.add_argument("--fast", action="store_true", help="print pytest cmd for touched groups")
    mode.add_argument("--gate", action="store_true", help="print pytest cmd for touched + always groups")
    mode.add_argument("--list", action="store_true", help="human summary of the selection")
    p.add_argument("--check", action="store_true", help="with --sync: verify in-sync, don't write")
    p.add_argument("--run", action="store_true", help="with --fast/--gate: run pytest instead of printing")
    p.add_argument("--json", action="store_true", help="machine-readable selection output")
    args = p.parse_args(argv)

    if args.sync:
        return _cmd_sync(args)

    catalog, sel, _ = _resolve_selection(args)
    if args.json:
        print(json.dumps(sel, indent=2))
        return 0
    if args.list:
        return _cmd_list(args)
    return _emit_command(catalog, sel, gate=args.gate, run=args.run)


if __name__ == "__main__":
    raise SystemExit(main())
